version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/src/authorizer/"
      - "/src/issuer_acmpca/"
      - "/src/issuer_iotcore/"
    schedule:
      interval: "weekly"
