AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >-
  AWS CloudFormation template for secretfree provisioning
Parameters:
  TemplateBucket:
    Default: elberger-secretfree-template
    Description: >-
      The S3 bucket into which the template, lambda functions, and Web
      content have been uploaded.
    Type: String
  SkuName:
    Default: widgiot
    Description: >-
      Usually the shortened product name, uniquely representing a
      product line. This is done to keep multiple product capabilities
      and certificate issuance separate from one another.
    Type: String
  AcmPcaCaArn:
    Default: put-your-arn-here
    Description: >-
      The CA Arn for ACM PCA CA.  Note that this value is not
      validated and is applied to the lambda function environment.
    Type: String
  CertValidityDays:
    Default: 180
    Description: >-
      ACM PCA cert generation: certificate validity in days.
    Type: Integer
  SigningAlgorithm:
    Default: SHA256WITHRSA
    Description: >-
      Valid ACM PCA signing algorithm used in vending the certificate.
    Type: String

Outputs:
  ProvisioningTableArn:
    Description: >-
      The ARN for the provisioning DynamoDB table.
    Value: !GetAtt ProvisioningTable.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProvisioningTableArn"
  ProvisioningTableStream:
    Description: >-
      The Stream ARN for the provisioning DynamoDB table.
    Value: !GetAtt ProvisioningTable.StreamArn
    Export:
      Name: !Sub "${AWS::StackName}-ProvisioningTableStream"
  ProvisioningTableName:
    Description: >-
      The simple name for the provisioning DynamoDB table.
    Value: !Ref ProvisioningTable
    Export:
      Name: !Sub "${AWS::StackName}-ProvisioningTableName"

Resources:
  PerSkuLambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${SkuName}-secretfree-authorizer
      CodeUri: src/authorizer
      Role: !GetAtt PerSkuLambdaAuthorizerExecutionRole.Arn
      Handler: main.lambda_handler
      Runtime: python3.13
      MemorySize: 1024
      Environment:
        Variables:
          SECRETFREE_TABLENAME: !Ref ProvisioningTable

  PerSkuLambdaAuthorizerLogGroup: 
    Type: AWS::Logs::LogGroup
    DependsOn:
      - PerSkuLambdaAuthorizer
    Properties: 
      RetentionInDays: 7
      LogGroupName: !Sub /aws/lambda/${SkuName}-secretfree-authorizer

  PerSkuLambdaAuthorizerInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ProvisioningMethodNewPost
    Properties:
      FunctionName: !GetAtt PerSkuLambdaAuthorizer.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ':'
        - - arn
          - aws
          - execute-api
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - !Sub ${ProvisioningRestApi}/authorizers/${ProvisioningAuthorizer}

  PerSkuLambdaAuthorizerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${SkuName}-secretfree-authorizer-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSIoTFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: !Sub ${SkuName}-secretfree-authorizer-logger
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              -
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${SkuName}-secretfree-authorizer:*

  PerSkuLambdaProvisioningACMPCA:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${SkuName}-secretfree-acmpca
      CodeUri: src/issuer-acmpca
      Role: !GetAtt PerSkuLambdaProvisioningACMPCARole.Arn
      Handler: main.lambda_handler
      Runtime: python3.13
      MemorySize: 1024
      Environment:
        Variables:
          ACMPCA_CA_ARN: !Ref AcmPcaCaArn
          SKUNAME: !Ref SkuName
          CERT_VALIDITY_DAYS: !Ref CertValidityDays
          CERT_SIGNING_ALGO: !Ref SigningAlgorithm

  PerSkuLambdaProvisioningACMPCALogGroup: 
    Type: AWS::Logs::LogGroup
    DependsOn:
      - PerSkuLambdaProvisioningACMPCA
    Properties: 
      RetentionInDays: 7
      LogGroupName: !Sub /aws/lambda/${SkuName}-secretfree-acmpca

  PerSkuLambdaProvisioningACMPCAInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ProvisioningMethodNewPost
    Properties:
      FunctionName: !GetAtt PerSkuLambdaProvisioningACMPCA.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !GetAtt ProvisioningMethodNewPost.Arn

  PerSkuLambdaProvisioningACMPCARole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${SkuName}-secretfree-provisioning-acmpca-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSIoTFullAccess
        - arn:aws:iam::aws:policy/AWSCertificateManagerPrivateCAFullAccess
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: !Sub ${SkuName}-secretfree-provisioning-acmpca-logger
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              -
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${SkuName}-secretfree-acmpca:*

  PerSkuLambdaProvisioningIotCore:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${SkuName}-secretfree-iotcore
      CodeUri: src/issuer-iotcore
      Role: !GetAtt PerSkuLambdaProvisioningIotCoreRole.Arn
      Handler: main.lambda_handler
      Runtime: python3.13
      MemorySize: 1024
      Environment:
        Variables:
          SKUNAME: !Ref SkuName

  PerSkuLambdaProvisioningIotCoreLogGroup: 
    Type: AWS::Logs::LogGroup
    DependsOn:
      - PerSkuLambdaProvisioningIotCore
    Properties: 
      RetentionInDays: 7
      LogGroupName: !Sub /aws/lambda/${SkuName}-secretfree-iotcore




  PerSkuLambdaIotCoreInvokePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ProvisioningMethodNewPost
    Properties:
      FunctionName: !GetAtt PerSkuLambdaProvisioningIotCore.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ':'
        - - arn
          - aws
          - execute-api
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - !Sub ${ProvisioningRestApi}/*/*/new-proto

  PerSkuLambdaProvisioningIotCoreRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: !Sub ${SkuName}-secretfree-provisioning-iotcore-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSIoTFullAccess
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: !Sub ${SkuName}-secretfree-provisioning-iotcore-logger
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: Allow
                Action: logs:CreateLogGroup
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
              -
                Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${SkuName}-secretfree-iotcore:*

  ProvisioningTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        -
          AttributeName: "device-id"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - 
          AttributeName: "device-id"
          KeyType: "HASH"
      TableName: !Sub ${SkuName}-iot-provisioning-secretfree
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ProvisioningRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${SkuName}-IoTProvisioning"
      Description: !Sub "This API enables certificate provisioning for the ${SkuName} product line."
      ApiKeySourceType: HEADER
      EndpointConfiguration:
        Types:
          - REGIONAL
    
  ProvisioningResourceNew:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ProvisioningRestApi
      ParentId:  !GetAtt ProvisioningRestApi.RootResourceId
      PathPart: new

  ProvisioningMethodNewPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ProvisioningRestApi
      ResourceId: !Ref ProvisioningResourceNew
      ApiKeyRequired: False
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ProvisioningAuthorizer
      HttpMethod: POST
      RequestParameters: { "method.request.header.device-csr": true }
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Join
          - ':'
          - - arn
            - aws
            - apigateway
            - !Ref AWS::Region
            - lambda
            - path/2015-03-31/functions/arn
            - aws
            - lambda
            - !Ref AWS::Region
            - !Ref AWS::AccountId
            - function
            - !Sub ${SkuName}-secretfree-acmpca/invocations
        RequestTemplates:
          application/json: >-
            {
            "method" : "$context.httpMethod",
            "body"   : $input.json('$'),
            "headers": {
              #foreach($param in $input.params().header.keySet())
              "$param" : "$util.escapeJavaScript($input.params().header.get($param))"
                  #if($foreach.hasNext),#end
              #end
            }
            }
        RequestParameters: { "integration.request.header.device-csr": "method.request.header.device-csr" }
        PassthroughBehavior: WHEN_NO_TEMPLATES
        ContentHandling: CONVERT_TO_TEXT
        TimeoutInMillis: 29000
        IntegrationResponses:
          - StatusCode: '200'
            ResponseTemplates: { "text/plain" : "$input.path('$')" }
      MethodResponses:
        - StatusCode: '200'
          ResponseModels: { }
    
  ProvisioningResourceProto:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ProvisioningRestApi
      ParentId:  !GetAtt ProvisioningRestApi.RootResourceId
      PathPart: proto

  ProvisioningMethodProtoPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ProvisioningRestApi
      ResourceId: !Ref ProvisioningResourceProto
      ApiKeyRequired: False
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref ProvisioningAuthorizer
      HttpMethod: POST
      RequestParameters: { "method.request.header.device-csr": true }
      Integration:
        Type: AWS
        IntegrationHttpMethod: POST
        Uri: !Join
          - ':'
          - - arn
            - aws
            - apigateway
            - !Ref AWS::Region
            - lambda
            - path/2015-03-31/functions/arn
            - aws
            - lambda
            - !Ref AWS::Region
            - !Ref AWS::AccountId
            - function
            - !Sub ${SkuName}-secretfree-iotcore/invocations
        RequestTemplates:
          application/json: >-
            {
            "method" : "$context.httpMethod",
            "body"   : $input.json('$'),
            "headers": {
              #foreach($param in $input.params().header.keySet())
              "$param" : "$util.escapeJavaScript($input.params().header.get($param))"
                  #if($foreach.hasNext),#end
              #end
            }
            }
        RequestParameters: { "integration.request.header.device-csr": "method.request.header.device-csr" }
        PassthroughBehavior: WHEN_NO_TEMPLATES
        ContentHandling: CONVERT_TO_TEXT
        TimeoutInMillis: 29000
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates: { "text/plain" : "$input.path('$')" }
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { }

  ProvisioningAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      AuthorizerResultTtlInSeconds: 0
      AuthorizerUri: !Join
        - ':' 
        - - arn
          - aws
          - apigateway
          - !Ref AWS::Region
          - lambda
          - path/2015-03-31/functions/arn
          - aws
          - lambda
          - !Ref AWS::Region
          - !Ref AWS::AccountId
          - function
          - !Sub ${SkuName}-secretfree-authorizer/invocations
      Type: REQUEST
      IdentitySource: method.request.header.device-csr
      Name: CsrAuthorizer
      RestApiId: !Ref ProvisioningRestApi

  ProvisioningDeploymentTest:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProvisioningResourceNew
      - ProvisioningMethodNewPost
      - ProvisioningResourceProto
      - ProvisioningMethodProtoPost
    Properties:
      StageName: Test
      RestApiId: !Ref ProvisioningRestApi
        
